name: Lint and format

on: pull_request
permissions: read-all
jobs:
  codestyle:
    runs-on: ubuntu-latest
    name: Codestyle
    steps:
      - name: Check out source repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v2.4.0
      - name: Set up Python environment
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v3.0.0
        with:
          python-version: "3.8"
      - name: flake8 Lint post process
        uses: py-actions/flake8@84ec6726560b6d5bd68f2a5bed83d62b52bb50ba # v2
        with:
          ignore: "E125,W503,W504,W605"
          max-line-length: "100"
          path: "src/"
      - name: flake8 Lint python frontend
        uses: py-actions/flake8@84ec6726560b6d5bd68f2a5bed83d62b52bb50ba # v2
        with:
          ignore: "E125,W503,W504,W605"
          max-line-length: "100"
          path: "frontends/python/"
      - name: Install yapf
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: yapf code formatting
        run: |
          yapf -d -r ./src/fuzz_introspector/
          yapf -d -r ./tools/auto-fuzz
          yapf -d -r ./tools/web-fuzzing-introspection/app/webapp/
          yapf -d ./tools/web-fuzzing-introspection/app/*.py
          yapf -d -r ./tools/web-fuzzing-introspection/app/static/assets/db
