name: Mypy

on:
  pull_request:
    paths:
      - 'src/**'
      - 'frontends/python/**'
      - 'oss_fuzz_integration/**'
      - '.github/workflows/mypy.yml'
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v2.4.0
    - name: Set up Python 3.10
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v3.0.0
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        pip install mypy types-PyYAML
    - name: Install FI as modules
      run: |
        cd src && pip install .
    - name: mypy
      run: |
        cd src && mypy --ignore-missing-imports -m main
