name: Mypy

on:
  pull_request:
    paths:
      - 'src/**'
      - 'frontends/python/**'
      - 'oss_fuzz_integration/**'
      - '.github/workflows/mypy.yml'
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    name: Mypy
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v2.4.0
    - name: Set up Python 3.8
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v3.0.0
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install mypy types-PyYAML
    - name: mypy
      run: |
        cd src && mypy --ignore-missing-imports -m main
