name: webapp-api-test

on:
  pull_request:
    branches:
      main
    paths:
      - 'tools/web-fuzzing-introspection/**'
      - '.github/helper/**'
      - '.github/workflows/webapp-api-test.yml'
permissions: read-all
jobs:
  build:
    runs-on: ubuntu-latest
    name: webapp-api-test
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v2.4.0
    - name: Set up Python 3.8
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v3.0.0
      with:
        python-version: 3.8
    - name: Install venv
      run: sudo apt-get install python3-venv
    - name: Set up venv
      run: python3 -m venv tools/web-fuzzing-introspection/.venv
    - name: Active venv dependencies
      run: source tools/web-fuzzing-introspection/.venv/bin/activate && pip install -r tools/web-fuzzing-introspection/requirements.txt
    - name: Run test
      run: source tools/web-fuzzing-introspection/.venv/bin/activate && python3 .github/helper/api_test.py
